logger:

    # Logger settings
    # Logs specific actions pertaining to souls

    # Enable/Disable this feature entirely
    enabled: true

    log-soul-spawns: true # Log soul spawns (when a soul is created)
    log-soul-pickups: true # Log soul pickups (when they are picked up by the player)
    log-soul-explosions: true # Log soul explosions (otherwise known as when they disappear)

    # Log format

    # Placeholders:
    # {soulOwner} for soul owner (player)
    # {x} for x coordinate
    # {y} for y coordinate
    # {z} for z coordinate
    # Formatted by ANSI color codes, NOT legacy or MiniMessage

    log-soul-spawns-message: "\u001B[37m[SoulTracker] \u001B[92mSoul spawned for \u001B[93m{soulOwner}\u001B[92m at \u001B[93m{x} {y} {z}\u001B[0m"
    log-soul-pickups-message: "\u001B[37m[SoulTracker] \u001B[93m{soulOwner}\u001B[92m picked up a soul at \u001B[93m{x} {y} {z}\u001B[0m"
    log-soul-explosions-message: "\u001B[37m[SoulTracker] \u001B[91mSoul for \u001B[93m{soulOwner}\u001B[91m exploded at \u001B[93m{x} {y} {z}\u001B[0m"


hologram:

    # Hologram settings
    # Holograms are displayed above the soul's grave
    # This features requires FancyHolograms or DecentHolograms

    # Enable/Disable this feature entirely
    enabled: true

    # Configure the location of the hologram relative to the soul's location
    x-offset: 0.0 # x-offset from the soul's location
    y-offset: 3.5 # y-offset from the soul's location
    z-offset: 0.0 # z-offset from the soul's location

    # Configure the background of the hologram, defaults to the default hologram background
    # This has no effect if you are using DecentHolograms
    custom-background: false # enable custom background
    background-color: "1,100,255,79" # ARGB format

    # Configure the text of the hologram, using MiniMessage and/or Legacy Formatting

    # Placeholders:
    # {soulOwner} for soul owner (player)
    # {formattedTime} for formatted time of death
    # {soulTime} for configured raw time for soul expiry
    # {formattedSoulTime} for configured time for soul expiry
    lines:
        - ""
        - "&b☠ &lSOUL GRAVE&r &8» &f{soulOwner}"
        - "&7Passed away at &f{formattedTime}"
        - ""
        - "&b [ᴛᴏᴜᴄʜ ᴛʜᴇ ɢʀᴀᴠᴇ ᴛᴏ ʀᴇᴛʀɪᴇᴠᴇ ᴇꜱꜱᴇɴᴄᴇ] &r"
        - ""

    # How fast should we update the holograms? (in ticks)
    update-ticks: 10

options:

    # Date format
    date-format: "yyyy-MM-dd HH:mm:ss"

    # Time format
    # {d} for days, {h} for hours, {m} for minutes, {s} for seconds
    time-format: "{m}m {s}s"