name: SoulGravesPlus
version: '${version}'
main: gg.jos.soulgravesplus.SoulGravesPlus
api-version: '1.21'
softdepend: [SoulGraves, FancyHolograms, DecentHolograms]
authors: [JosTheDude]
website: https://jos.gg/

commands:
  soulgravesplus:
    description: Main command for SoulGravesPlus
    usage: /soulgravesplus
    permission: soulgravesplus.admin